table.name = UrlsTable

aws.dynamodb.region=us-east-1
aws.dynamodb.endpoint=https://dynamodb.${aws.dynamodb.region}.amazonaws.com

spring.redis.database=0
spring.redis.host=localhost
spring.redis.port=16379
spring.redis.password=mypass
spring.redis.timeout=60000
