spring.application.name=URL Shortener

table.name=UrlsTable

amazon.dynamodb.region=us-east-1
amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=key1
amazon.aws.secretkey=key2

spring.redis.database=0
spring.redis.host=localhost
spring.redis.port=16379
spring.redis.password=mypass
spring.redis.timeout=60000
